package org.hmk.find_itinerary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Test {
    public static void main(String[] args) {
        Solution solution = new Solution();

        List<List<String>> input1 = new ArrayList<>();
        input1.add(Arrays.asList("MUC","LHR"));
        input1.add(Arrays.asList("JFK","MUC"));
        input1.add(Arrays.asList("SFO","SJC"));
        input1.add(Arrays.asList("LHR","SFO"));
//        System.out.println(solution.findItinerary(input1));


        input1 = new ArrayList<>();
        input1.add(Arrays.asList("JFK","SFO"));
        input1.add(Arrays.asList("JFK","ATL"));
        input1.add(Arrays.asList("SFO","ATL"));
        input1.add(Arrays.asList("ATL","JFK"));
        input1.add(Arrays.asList("ATL","SFO"));
//        System.out.println(solution.findItinerary(input1));

        input1 = new ArrayList<>();
        input1.add(Arrays.asList("JFK","AAA"));
        input1.add(Arrays.asList("AAA","JFK"));
        input1.add(Arrays.asList("JFK","BBB"));
        input1.add(Arrays.asList("JFK","CCC"));
        input1.add(Arrays.asList("CCC","JFK"));
//        System.out.println(solution.findItinerary(input1));

        input1 = new ArrayList<>();
        input1.add(Arrays.asList("AXA","EZE"));
        input1.add(Arrays.asList("EZE","AUA"));
        input1.add(Arrays.asList("ADL","JFK"));
        input1.add(Arrays.asList("ADL","TIA"));
        input1.add(Arrays.asList("AUA","AXA"));
        input1.add(Arrays.asList("EZE","TIA"));
        input1.add(Arrays.asList("EZE","TIA"));
        input1.add(Arrays.asList("AXA","EZE"));
        input1.add(Arrays.asList("EZE","ADL"));
        input1.add(Arrays.asList("ANU","EZE"));
        input1.add(Arrays.asList("TIA","EZE"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("AUA","JFK"));
        input1.add(Arrays.asList("JFK","EZE"));
        input1.add(Arrays.asList("EZE","ANU"));
        input1.add(Arrays.asList("ADL","AUA"));
        input1.add(Arrays.asList("ANU","AXA"));
        input1.add(Arrays.asList("AXA","ADL"));
        input1.add(Arrays.asList("AUA","JFK"));
        input1.add(Arrays.asList("EZE","ADL"));
        input1.add(Arrays.asList("ANU","TIA"));
        input1.add(Arrays.asList("AUA","JFK"));
        input1.add(Arrays.asList("TIA","JFK"));
        input1.add(Arrays.asList("EZE","AUA"));
        input1.add(Arrays.asList("AXA","EZE"));
        input1.add(Arrays.asList("AUA","ANU"));
        input1.add(Arrays.asList("ADL","AXA"));
        input1.add(Arrays.asList("EZE","ADL"));
        input1.add(Arrays.asList("AUA","ANU"));
        input1.add(Arrays.asList("AXA","EZE"));
        input1.add(Arrays.asList("TIA","AUA"));
        input1.add(Arrays.asList("AXA","EZE"));
        input1.add(Arrays.asList("AUA","SYD"));
        input1.add(Arrays.asList("ADL","JFK"));
        input1.add(Arrays.asList("EZE","AUA"));
        input1.add(Arrays.asList("ADL","ANU"));
        input1.add(Arrays.asList("AUA","TIA"));
        input1.add(Arrays.asList("ADL","EZE"));
        input1.add(Arrays.asList("TIA","JFK"));
        input1.add(Arrays.asList("AXA","ANU"));
        input1.add(Arrays.asList("JFK","AXA"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("ADL","EZE"));
        input1.add(Arrays.asList("AXA","TIA"));
        input1.add(Arrays.asList("JFK","AUA"));
        input1.add(Arrays.asList("ADL","EZE"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("ADL","AXA"));
        input1.add(Arrays.asList("TIA","AUA"));
        input1.add(Arrays.asList("AXA","JFK"));
        input1.add(Arrays.asList("ADL","AUA"));
        input1.add(Arrays.asList("TIA","JFK"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("ANU","AXA"));
        input1.add(Arrays.asList("TIA","AXA"));
        input1.add(Arrays.asList("EZE","JFK"));
        input1.add(Arrays.asList("EZE","AXA"));
        input1.add(Arrays.asList("ADL","TIA"));
        input1.add(Arrays.asList("JFK","AUA"));
        input1.add(Arrays.asList("TIA","EZE"));
        input1.add(Arrays.asList("EZE","ADL"));
        input1.add(Arrays.asList("JFK","ANU"));
        input1.add(Arrays.asList("TIA","AUA"));
        input1.add(Arrays.asList("EZE","ADL"));
        input1.add(Arrays.asList("ADL","JFK"));
        input1.add(Arrays.asList("ANU","AXA"));
        input1.add(Arrays.asList("AUA","AXA"));
        input1.add(Arrays.asList("ANU","EZE"));
        input1.add(Arrays.asList("ADL","AXA"));
        input1.add(Arrays.asList("ANU","AXA"));
        input1.add(Arrays.asList("TIA","ADL"));
        input1.add(Arrays.asList("JFK","ADL"));
        input1.add(Arrays.asList("JFK","TIA"));
        input1.add(Arrays.asList("AUA","ADL"));
        input1.add(Arrays.asList("AUA","TIA"));
        input1.add(Arrays.asList("TIA","JFK"));
        input1.add(Arrays.asList("EZE","JFK"));
        input1.add(Arrays.asList("AUA","ADL"));
        input1.add(Arrays.asList("ADL","AUA"));
        input1.add(Arrays.asList("EZE","ANU"));
        input1.add(Arrays.asList("ADL","ANU"));
        input1.add(Arrays.asList("AUA","AXA"));
        input1.add(Arrays.asList("AXA","TIA"));
        input1.add(Arrays.asList("AXA","TIA"));
        input1.add(Arrays.asList("ADL","AXA"));
        input1.add(Arrays.asList("EZE","AXA"));
        input1.add(Arrays.asList("AXA","JFK"));
        input1.add(Arrays.asList("JFK","AUA"));
        input1.add(Arrays.asList("ANU","ADL"));
        input1.add(Arrays.asList("AXA","TIA"));
        input1.add(Arrays.asList("ANU","AUA"));
        input1.add(Arrays.asList("JFK","EZE"));
        input1.add(Arrays.asList("AXA","ADL"));
        input1.add(Arrays.asList("TIA","EZE"));
        input1.add(Arrays.asList("JFK","AXA"));
        input1.add(Arrays.asList("AXA","ADL"));
        input1.add(Arrays.asList("EZE","AUA"));
        input1.add(Arrays.asList("AXA","ANU"));
        input1.add(Arrays.asList("ADL","EZE"));
        input1.add(Arrays.asList("AUA","EZE"));

        System.out.println(solution.findItinerary(input1));
    }
}
